FROM node:20-bullseye AS build
WORKDIR /app
RUN apt-get update && apt-get install -y \
    build-essential \
    libcairo2-dev \
    libjpeg-dev \
    libpango1.0-dev \
    libgif-dev \
    librsvg2-dev \
    python3 \
    && rm -rf /var/lib/apt/lists/*
COPY package*.json ./
RUN npm install --include=optional

COPY . .

ENV POSTGRES_URI="postgresql://dummy:dummy@localhost:5432/dummy"
RUN npx prisma generate
RUN NODE_OPTIONS="--max-old-space-size=4096" npm run build

FROM node:20-bookworm-slim AS prod

WORKDIR /app

RUN apt-get update && apt-get install -y \
    openssl \
    libcairo2 \
    libjpeg62-turbo \
    libpango-1.0-0 \
    libgif7 \
    librsvg2-2 \
    && rm -rf /var/lib/apt/lists/*

COPY --from=build /app/package*.json ./
COPY --from=build /app/prisma ./prisma
COPY --from=build /app/dist ./dist

COPY --from=build /app/node_modules ./node_modules

EXPOSE 4000

CMD ["node", "dist/src/main.js"]
