
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.17.0
 * Query Engine version: c0aafc03b8ef6cdced8654b9a817999e02457d6a
 */
Prisma.prismaVersion = {
  client: "6.17.0",
  engine: "c0aafc03b8ef6cdced8654b9a817999e02457d6a"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  password: 'password',
  displayName: 'displayName',
  picture: 'picture',
  isVerified: 'isVerified',
  isTwoFactorEnabled: 'isTwoFactorEnabled',
  method: 'method',
  role: 'role',
  secondName: 'secondName',
  studentIdFront: 'studentIdFront',
  studentIdBack: 'studentIdBack',
  isActive: 'isActive',
  startReservationDate: 'startReservationDate',
  endReservationDate: 'endReservationDate',
  dormitoryId: 'dormitoryId',
  roomId: 'roomId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.DormitoryAdminScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  dormitoryId: 'dormitoryId',
  role: 'role',
  createdAt: 'createdAt'
};

exports.Prisma.ConfirmationScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  status: 'status',
  photo: 'photo',
  frontIdUrl: 'frontIdUrl',
  backIdUrl: 'backIdUrl',
  createdAt: 'createdAt',
  resolvedAt: 'resolvedAt',
  rejectionReason: 'rejectionReason',
  roomId: 'roomId',
  from: 'from',
  to: 'to',
  roommateIds: 'roommateIds',
  numberOfPeople: 'numberOfPeople',
  metadata: 'metadata'
};

exports.Prisma.TokenScalarFieldEnum = {
  id: 'id',
  email: 'email',
  token: 'token',
  type: 'type',
  expiresIn: 'expiresIn'
};

exports.Prisma.AuditLogScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  action: 'action',
  entity: 'entity',
  entityId: 'entityId',
  meta: 'meta',
  createdAt: 'createdAt'
};

exports.Prisma.DormitoryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  address: 'address',
  groundFloorPhoneNumber: 'groundFloorPhoneNumber',
  status: 'status',
  photos: 'photos',
  managerId: 'managerId',
  createdAt: 'createdAt'
};

exports.Prisma.FloorScalarFieldEnum = {
  id: 'id',
  floorNumber: 'floorNumber',
  dormitoryId: 'dormitoryId'
};

exports.Prisma.RoomScalarFieldEnum = {
  id: 'id',
  number: 'number',
  floorId: 'floorId',
  capacity: 'capacity',
  dormitoryId: 'dormitoryId',
  roomEquipment: 'roomEquipment',
  photos: 'photos',
  roomTypeId: 'roomTypeId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.RoomTypeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  capacity: 'capacity',
  equipment: 'equipment',
  typeCode: 'typeCode',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FloorRoomAssignmentScalarFieldEnum = {
  id: 'id',
  floorId: 'floorId',
  roomTypeId: 'roomTypeId',
  roomNumbers: 'roomNumbers'
};

exports.Prisma.RoomStatusScalarFieldEnum = {
  id: 'id',
  roomId: 'roomId',
  dateOfStart: 'dateOfStart',
  dateOfEnd: 'dateOfEnd',
  description: 'description'
};

exports.Prisma.PriceScalarFieldEnum = {
  id: 'id',
  roomId: 'roomId',
  roomCapacity: 'roomCapacity',
  pricePerMonth: 'pricePerMonth',
  pricePerDay: 'pricePerDay',
  dateFrom: 'dateFrom',
  dateTo: 'dateTo'
};

exports.Prisma.BookingScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  roomId: 'roomId',
  status: 'status',
  checkInDate: 'checkInDate',
  checkOutDate: 'checkOutDate',
  totalAmount: 'totalAmount',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PaymentScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  bookingId: 'bookingId',
  priceId: 'priceId',
  amount: 'amount',
  currency: 'currency',
  paymentType: 'paymentType',
  paymentMethod: 'paymentMethod',
  status: 'status',
  dueDate: 'dueDate',
  paidAt: 'paidAt',
  description: 'description',
  paymentProofUrl: 'paymentProofUrl',
  paymentProofFilename: 'paymentProofFilename',
  paymentProofUploadedAt: 'paymentProofUploadedAt',
  externalPaymentId: 'externalPaymentId',
  failureReason: 'failureReason',
  managerNotes: 'managerNotes',
  confirmedBy: 'confirmedBy',
  confirmedAt: 'confirmedAt',
  rejectedAt: 'rejectedAt',
  rejectionReason: 'rejectionReason',
  recurringPaymentId: 'recurringPaymentId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.RecurringPaymentScalarFieldEnum = {
  id: 'id',
  paymentId: 'paymentId',
  bookingId: 'bookingId',
  frequency: 'frequency',
  startDate: 'startDate',
  endDate: 'endDate',
  dayOfMonth: 'dayOfMonth',
  isActive: 'isActive',
  lastProcessed: 'lastProcessed',
  nextDueDate: 'nextDueDate',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PaymentItemScalarFieldEnum = {
  id: 'id',
  paymentId: 'paymentId',
  itemType: 'itemType',
  description: 'description',
  amount: 'amount',
  period: 'period'
};

exports.Prisma.PaymentAuditLogScalarFieldEnum = {
  id: 'id',
  paymentId: 'paymentId',
  userId: 'userId',
  action: 'action',
  oldValue: 'oldValue',
  newValue: 'newValue',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  createdAt: 'createdAt'
};

exports.Prisma.NotificationScalarFieldEnum = {
  id: 'id',
  type: 'type',
  title: 'title',
  message: 'message',
  priority: 'priority',
  fromUserId: 'fromUserId',
  toUserId: 'toUserId',
  roomId: 'roomId',
  bookingId: 'bookingId',
  paymentId: 'paymentId',
  isRead: 'isRead',
  isArchived: 'isArchived',
  readAt: 'readAt',
  archivedAt: 'archivedAt',
  metadata: 'metadata',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.NotificationSettingsScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  emailNotifications: 'emailNotifications',
  emailPaymentReminders: 'emailPaymentReminders',
  emailBookingUpdates: 'emailBookingUpdates',
  emailAnnouncements: 'emailAnnouncements',
  inAppNotifications: 'inAppNotifications',
  markAsReadOnView: 'markAsReadOnView',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AnnouncementScalarFieldEnum = {
  id: 'id',
  title: 'title',
  content: 'content',
  authorId: 'authorId',
  isHidden: 'isHidden',
  postedAt: 'postedAt',
  expiresAt: 'expiresAt'
};

exports.Prisma.AttachmentScalarFieldEnum = {
  id: 'id',
  announcementId: 'announcementId',
  url: 'url',
  filename: 'filename'
};

exports.Prisma.AnnouncementRecipientScalarFieldEnum = {
  id: 'id',
  announcementId: 'announcementId',
  userId: 'userId',
  roomId: 'roomId',
  floor: 'floor',
  forEveryone: 'forEveryone'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};
exports.AuthMethod = exports.$Enums.AuthMethod = {
  CREDENTIALS: 'CREDENTIALS',
  GOOGLE: 'GOOGLE',
  LOCAL: 'LOCAL'
};

exports.UserRole = exports.$Enums.UserRole = {
  Regular: 'Regular',
  Admin: 'Admin',
  SignedInUser: 'SignedInUser',
  SuperAdmin: 'SuperAdmin',
  Resident: 'Resident'
};

exports.ConfirmationType = exports.$Enums.ConfirmationType = {
  IDENTITY_VERIFICATION: 'IDENTITY_VERIFICATION',
  ACCOMMODATION: 'ACCOMMODATION',
  ROOM_CHANGE: 'ROOM_CHANGE',
  ROOM_VACATION: 'ROOM_VACATION'
};

exports.ConfirmationStatus = exports.$Enums.ConfirmationStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
};

exports.TokenType = exports.$Enums.TokenType = {
  VERIFICATION: 'VERIFICATION',
  TWO_FACTOR: 'TWO_FACTOR',
  PASSWORD_RESET: 'PASSWORD_RESET'
};

exports.BookingStatus = exports.$Enums.BookingStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
  COMPLETED: 'COMPLETED'
};

exports.PaymentType = exports.$Enums.PaymentType = {
  MONTHLY_RENT: 'MONTHLY_RENT',
  DAILY_RENT: 'DAILY_RENT',
  SECURITY_DEPOSIT: 'SECURITY_DEPOSIT',
  UTILITIES: 'UTILITIES',
  MAINTENANCE_FEE: 'MAINTENANCE_FEE',
  LATE_FEE: 'LATE_FEE',
  CLEANING_FEE: 'CLEANING_FEE',
  OTHER: 'OTHER'
};

exports.PaymentMethod = exports.$Enums.PaymentMethod = {
  STRIPE_CARD: 'STRIPE_CARD',
  CASH_TO_MANAGER: 'CASH_TO_MANAGER',
  BANK_TRANSFER: 'BANK_TRANSFER',
  OTHER: 'OTHER'
};

exports.PaymentStatus = exports.$Enums.PaymentStatus = {
  PENDING: 'PENDING',
  AWAITING_CONFIRMATION: 'AWAITING_CONFIRMATION',
  PROCESSING: 'PROCESSING',
  PAID: 'PAID',
  FAILED: 'FAILED',
  OVERDUE: 'OVERDUE',
  CANCELLED: 'CANCELLED',
  REFUNDED: 'REFUNDED',
  PARTIAL_REFUND: 'PARTIAL_REFUND',
  REJECTED: 'REJECTED'
};

exports.RecurringFrequency = exports.$Enums.RecurringFrequency = {
  MONTHLY: 'MONTHLY',
  WEEKLY: 'WEEKLY',
  CUSTOM: 'CUSTOM'
};

exports.PaymentItemType = exports.$Enums.PaymentItemType = {
  RENT: 'RENT',
  SECURITY_DEPOSIT: 'SECURITY_DEPOSIT',
  UTILITIES: 'UTILITIES',
  MAINTENANCE_FEE: 'MAINTENANCE_FEE',
  LATE_FEE: 'LATE_FEE',
  CLEANING_FEE: 'CLEANING_FEE',
  OTHER: 'OTHER'
};

exports.NotificationType = exports.$Enums.NotificationType = {
  ROOM_BOOKING_REQUEST: 'ROOM_BOOKING_REQUEST',
  ROOM_BOOKING_APPROVED: 'ROOM_BOOKING_APPROVED',
  ROOM_BOOKING_REJECTED: 'ROOM_BOOKING_REJECTED',
  ROOM_ASSIGNMENT_UPDATED: 'ROOM_ASSIGNMENT_UPDATED',
  ROOM_AVAILABLE: 'ROOM_AVAILABLE',
  ACCOMMODATION_CHANGE_REQUEST: 'ACCOMMODATION_CHANGE_REQUEST',
  ACCOMMODATION_CHANGE_APPROVED: 'ACCOMMODATION_CHANGE_APPROVED',
  ACCOMMODATION_CHANGE_REJECTED: 'ACCOMMODATION_CHANGE_REJECTED',
  MAINTENANCE_SCHEDULED: 'MAINTENANCE_SCHEDULED',
  MAINTENANCE_COMPLETED: 'MAINTENANCE_COMPLETED',
  MAINTENANCE_URGENT: 'MAINTENANCE_URGENT',
  ADMIN_ANNOUNCEMENT: 'ADMIN_ANNOUNCEMENT',
  POLICY_UPDATE: 'POLICY_UPDATE',
  SYSTEM_MAINTENANCE: 'SYSTEM_MAINTENANCE',
  STUDENT_MESSAGE: 'STUDENT_MESSAGE',
  ROOMMATE_REQUEST: 'ROOMMATE_REQUEST',
  ROOMMATE_APPROVED: 'ROOMMATE_APPROVED',
  ACCOUNT_VERIFIED: 'ACCOUNT_VERIFIED',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  LOGIN_ALERT: 'LOGIN_ALERT',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  ACCOUNT_CREATED: 'ACCOUNT_CREATED',
  PAYMENT_REJECTED: 'PAYMENT_REJECTED',
  PAYMENT_CREATED: 'PAYMENT_CREATED',
  PAYMENT_DUE: 'PAYMENT_DUE',
  PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
  PAYMENT_OVERDUE: 'PAYMENT_OVERDUE',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_REMINDER: 'PAYMENT_REMINDER',
  PAYMENT_CONFIRMATION_REQUIRED: 'PAYMENT_CONFIRMATION_REQUIRED',
  PAYMENT_CONFIRMED: 'PAYMENT_CONFIRMED',
  PAYMENT_REFUNDED: 'PAYMENT_REFUNDED'
};

exports.NotificationPriority = exports.$Enums.NotificationPriority = {
  LOW: 'LOW',
  NORMAL: 'NORMAL',
  HIGH: 'HIGH',
  URGENT: 'URGENT'
};

exports.Prisma.ModelName = {
  User: 'User',
  DormitoryAdmin: 'DormitoryAdmin',
  Confirmation: 'Confirmation',
  Token: 'Token',
  AuditLog: 'AuditLog',
  Dormitory: 'Dormitory',
  Floor: 'Floor',
  Room: 'Room',
  RoomType: 'RoomType',
  FloorRoomAssignment: 'FloorRoomAssignment',
  RoomStatus: 'RoomStatus',
  Price: 'Price',
  Booking: 'Booking',
  Payment: 'Payment',
  RecurringPayment: 'RecurringPayment',
  PaymentItem: 'PaymentItem',
  PaymentAuditLog: 'PaymentAuditLog',
  Notification: 'Notification',
  NotificationSettings: 'NotificationSettings',
  Announcement: 'Announcement',
  Attachment: 'Attachment',
  AnnouncementRecipient: 'AnnouncementRecipient'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
